In [137]:
#import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error
from prettytable import PrettyTable

In [138]:
#Read the file "Advertising.csv"
df = pd.read_csv("Advertising.csv")
#Take a quick look at the data to list all the predictors
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [140]:
### edTest(test_mse) ###
#List to store the MSE values
mse_list = []

#List of all predictor combinations to fit the curve
cols = [['TV'],['Radio'],['Newspaper'],['TV','Radio'],['TV','Newspaper'],['Radio','Newspaper'],['TV','Radio','Newspaper']]

for i in cols:
    #Set each of the predictors from the previous list as x
    x = df[i]
    
    
    #"Sales" column is the reponse variable
    y = df[['Sales']]
    
   
    #Splitting the data into train-test sets with 80% training data and 20% testing data. 
    #Set random_state as 0
    xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size=0.8, random_state=None)

    #Create a LinearRegression object and fit the model
    lreg = LinearRegression()
    lreg.fit(xtrain, ytrain)
    
    #Predict the response variable for the test set
    y_pred= lreg.predict(xtest)
    
    #Compute the MSE
    MSE = mean_squared_error(y_pred, ytest)
    
    #Append the MSE to the list
    mse_list.append(MSE)

In [141]:
t = PrettyTable(['Predictors', 'MSE'])

#Loop to display the predictor combinations along with the MSE value of the corresponding model
for i in range(len(mse_list)):
    t.add_row([cols[i],mse_list[i]])

print(t)

+------------------------------+--------------------+
|          Predictors          |        MSE         |
+------------------------------+--------------------+
|            ['TV']            |  7.19685395052679  |
|          ['Radio']           | 18.53758065788718  |
|        ['Newspaper']         | 20.739600075853254 |
|       ['TV', 'Radio']        | 3.6531517880117583 |
|     ['TV', 'Newspaper']      | 9.751771023776747  |
|    ['Radio', 'Newspaper']    | 16.32492714910473  |
| ['TV', 'Radio', 'Newspaper'] | 3.1057766392159296 |
+------------------------------+--------------------+

In [142]:
#the more predictor, the less the MSE